version: "3"
services:
    db:
        container_name: mydb
        image: mysql:latest
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
    app:
        container_name: myapp
        links:
            - "db"
        build: ./
        ports:
            - "5001:5000"