apiVersion: v1
kind: Secret
metadata:
  name: do-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    eyJhdXRocyI6eyJyZWdpc3RyeS5kaWdpdGFsb2NlYW4uY29tIjp7ImF1dGgiOiJaRzl2WDNZeFh6WmpOMk5sTjJGbE5qZ3lPR1UzWW1ReU9Ua3lOVE14WlRFeU16RXlaVFEzWXpoa05qSmxabVEzTVRRMk5Ea3daR1k0WW1VNE1XWTJOMkk1WldKak5URTZaRzl2WDNZeFh6WmpOMk5sTjJGbE5qZ3lPR
